apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rrw629kz1-nodejs
  janus-idp.io/tekton: rrw629kz1-nodejs
  backstage.io/kubernetes-id: rrw629kz1-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rrw629kz1-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
